apiVersion: apps/v1
kind: Deployment
metadata:
  name: App-Deploy
  labels:
    app: App-Deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: App-Deploy
  template:
    metadata:
      labels:
        app: App-Deploy
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: App_Deploy
        image: chrisjonathan02/youtube-clone:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 3000
